kind: pipeline
name: pipeline

steps:
- name: publish
  image: plugins/docker
  settings:
    repo: pingu/kontena-logger
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    status: [ success ]
    branch: [ master ]
